freeCodeCamp-2025-Summer-Hackathon/purple-array

contribution-guidelines.md
Checklist:
Does not relate to any open issues or feature requests
=> docs: add contribution guidelines

README.md
Checklist:
**_This PR updates our README.md documentation with updated instructions for setting up MognoDB._**
Does not relate to any open issue
=> docs: update readme with db setup instructions

backend/src/server.js
=> fix: update server port

.gitignore
Added node-modules back to .gitignore file
Checklist:
Closes #XXXXX
=> docs: add node-modules to .gitignore

frontend/src/App.jsx, frontend/src/pages/JournalEntryDetailPage.jsx
Checklist:
Closes #49 
- Added a JournalEntryDetail Page
- Added a new Route for that page in the App.jsx component
=> feat: add journal entry detail page to the FE

frontend/src/components/home/JournalEntry.jsx, frontend/src/components/journal/JournalEntry.jsx, frontend/src/lib/utils.js, frontend/src/pages/JournalPage.jsx
Created basic journal entry component. created a utils.js with a format date function in lib directory.
*JournalEntry component is loaded into JournalPage to verify basic structure*
Checklist:
Closes #41
=> feat: add journal entry component

frontend/package-lock.json, frontend/package.json, frontend/src/components/generic/Navbar.jsx
Checklist:
Closes #51
- Added the Lucide package to our repository
- Added a 'journal' icon to the Navbar to demo usage and styling
=> feat: add Lucide icon package and update Navbar with icon

frontend/src/App.jsx, frontend/src/components/Home/WordOfTheDay.jsx, frontend/src/components/generic/Navbar.jsx, frontend/src/components/journal/JournalEntry.jsx, frontend/src/main.jsx, frontend/src/pages/HomePage.jsx, frontend/src/pages/JournalPage.jsx, frontend/src/pages/MarketPage.jsx, frontend/src/pages/SettingsPage.jsx, frontend/src/pages/SignInPage.jsx, frontend/tailwind.config.js
Checklist:
Closes #92 
This touches a lot of files, but mostly in minor ways:
- updates navbar with color, icons, & hover effects
- sets uniform height for page containers & components
- sets uniform width for home, journal, & market pages - settings page width is slightly less
**_additionally some changes are just files being reformatted to keep in line with my local linting configuration_**
=> style: set unified site styles with neutral base & single color

backend/src/models/word.js, backend/src/routes/words.js
Checklist:
- [ x] I have read and agree to adhere to the [Contribution Guidelines](https://github.com/freeCodeCamp-2025-Summer-Hackathon/purple-array/blob/main/contribution-guidelines.md).
- [ x] My pull request targets the `main` branch of the repository.
- [x ] I have tested these changes either locally on my machine, or Gitpod.
Closes #12
=> Finish Basic Word Schema

frontend/src/App.jsx, frontend/src/pages/HomePage.jsx, frontend/src/pages/JournalCollectionPage.jsx, frontend/src/pages/MarketPage.jsx
Add JournalCollectionPage.jsx to src/pages, update <Routes /> in App.jsx, remove no longer needed import react statement
Checklist:
Closes #120
=> feat: add journal collection page

frontend/src/components/Home/WordOfTheDay.jsx
=> feat: Update WordOfTheDay.jsx

frontend/src/App.jsx
Checklist:
does not relate to any issue
=> fix: remove depreceated component

frontend/public/marketDummyData.json, frontend/src/components/Market/MarketItems.jsx
Checklist:
Closes #103
I created the dummy data and changed the marketitems component to match the data. The styles aren't great but everything structually is there (I think).
=> feat: created dummy data and changed market items to match the data

.gitignore
added .DS_Store in addition to .DS_Store? to the .gitigore file
Checklist:
Relates to issue on PR #132
=> docs: [fix] update .gitignore

backend/package-lock.json, backend/src/controllers/inventoryController.js, backend/src/routes/inventoryRoutes.js, backend/src/server.js
=> Added GET /inventory

backend/src/models/Journal.js
Checklist:
- [ x] I have read and agree to adhere to the [Contribution Guidelines](https://github.com/freeCodeCamp-2025-Summer-Hackathon/purple-array/blob/main/contribution-guidelines.md).
- [ x] My pull request targets the `main` branch of the repository.
- [x ] I have tested these changes either locally on my machine, or Gitpod.
Closes #79
=> journal schema

README.md
remove inactive contributors from the README.md file
Checklist:
Closes #154
=> Docs: Update README.md contributors list

frontend/src/components/journal/JournalEntry.jsx, frontend/src/util/hooks/useWord.js
Checklist:
Does not relate to any open issues
=> fix: remove log and update dependency array

frontend/src/components/journal/JournalEntry.jsx, frontend/src/components/journal/JournalEntryForm.jsx, frontend/src/components/journal/JournalStyleCreateEdit.jsx, frontend/src/pages/JournalEditPage.jsx
Checklist:
Closes #165 
---
---
---
---
- created dropdown options for additional prompts
- styled the journal entry form
- added coin amount examples for amount given per prompt filled out (can change amounts or remove these if they're not necessary)
---
- moved a few buttons around for styling
=> style: Journal entry form styled

frontend/src/components/Home/WordOfTheDay.jsx, frontend/src/components/generic/AnimatePulseLoader.jsx
=> Refactor: create discrete component out of animate pulse loading div

frontend/package-lock.json, frontend/package.json, frontend/src/App.jsx, frontend/src/components/Home/WordOfTheDay.jsx, frontend/src/components/Market/MarketItems.jsx, frontend/src/components/generic/Navbar.jsx, frontend/src/components/journal/JournalEntry.jsx, frontend/src/components/journal/JournalEntryForm.jsx, frontend/src/pages/JournalDisplayPage.jsx, frontend/src/pages/MarketPage.jsx
Checklist:
This PR add tweaks to the feat/nav-indicators branch
=> fix [refactor]: fix bugs and tweak navbar styles

backend/src/controllers/productsController.js, backend/src/routes/productsRoutes.js
Checklist:
- [x ] I have read and agree to adhere to the [Contribution Guidelines](https://github.com/freeCodeCamp-2025-Summer-Hackathon/purple-array/blob/main/contribution-guidelines.md).
- [x ] My pull request targets the `main` branch of the repository.
- [x ] I have tested these changes either locally on my machine, or Gitpod.
Closes #XXXXX (doenst close any just a create Product route and controller)
=> Finished with postProduct

backend/src/models/Rewards.js
=> Added Rewards.js schema

frontend/public/timezones.json
Checklist:
Closes #189 
This PR just populates a list of timezones based on the IANA standards into a .json file
@haednodik @Mystel Will you both look at these and see if they look as they should, when you get a moment?
=> docs: set up timezones .json

frontend/src/components/journal/CollectionListCard.jsx, frontend/src/components/journal/JournalEntriesList.jsx
=> refactor/style: create card component for collection list and update word style

frontend/src/util/api/settings.js, frontend/src/util/hooks/useSettings.js
=> refactor: write useSettings to make use of axios and call to db

backend/src/server.js, frontend/src/components/settings/SettingsOptions.jsx, frontend/src/util/api/settings.js
Checklist:
Closes #219 
- add updateSettings helper function to the `/frontend/src/util/api/settings.js' file
- updates CORS methods to include the `PATCH` method in the `/backend/src/server.js`
=> feat: write updateSettings helper function

frontend/src/util/hooks/useAuth.js
Checklist:
does not relate to any issue
=> fix: add missing dependency array to useAuth Hook useEffect

frontend/src/util/api/entries.js
=> feat: Add updateEntry helper function for journal API (#109)

frontend/src/pages/LoginPage.jsx
=> style: Match login page with signup page

frontend/src/util/api/entries.js
Checklist:
Does not relate to any open issues
=> hotfix: refactor functions in entries.js

frontend/src/components/journal/JournalEntryForm.jsx
=> feat: Show journal entry data in form if it exists (#212)

frontend/src/components/Market/MarketItems.jsx
Checklist:
Not connected issue
=> hotfix: fix breaking change in Market Items Component

frontend/src/components/Market/MarketItems.jsx, frontend/src/util/api/coins.js, frontend/src/util/api/inventory.js, frontend/src/util/api/products.js, frontend/src/util/hooks/useCoins.js, frontend/src/util/hooks/useInventory.js, frontend/src/util/hooks/usePurchase.js
add refreshInventory function to useInventory hook, create usePurchase hook
Checklist:
Closes #223 
Resized images as well.
=> feat: add purchase functionality

backend/src/controllers/journalController.js
Checklist:
Closes #XXXXX
Validates date string formatting (####-##-##). Does NOT check whether date is valid (this will eventually be done once we can get the user's local time)
=> feat: validate date string format

frontend/src/components/Market/MarketItems.jsx, frontend/src/components/journal/JournalEntry.jsx, frontend/src/components/journal/JournalEntryForm.jsx, frontend/src/pages/MarketPage.jsx
Checklist:
Closes #262 
I didn't add the background color behind the coin balance on the journal page because it looked kinda funky right next to the gray background color of the box, I think it's fine that the market page has the background color and the journal page doesn't. Let me know if you disagree!
=> style: added coin balances on journal and market page

frontend/src/components/Market/MarketEmpty.jsx, frontend/src/components/Market/MarketItems.jsx, frontend/src/styles/index.css
=> feat: empty market page blurb added

frontend/src/components/generic/Navbar.jsx, frontend/src/pages/HomePage.jsx, frontend/src/pages/JournalDisplayPage.jsx, frontend/src/pages/LoginPage.jsx, frontend/src/pages/MarketPage.jsx, frontend/src/pages/SettingsPage.jsx, frontend/src/pages/SignupPage.jsx
Checklist:
Closes #266 
- sets conditional visibility for logout button so that it's only visible when user is logged in
- grabs email during login/signup to stash in localstorage to make use of in navbar while user is logged in
=> feat: update navbar w/user email & make logout conditional

frontend/public/placeholderMarketItems.json
Checklist:
Does not relate to any open issues
=> feat[style]: add new thems to placeholder data for later implementation

backend/src/models/User.js, frontend/src/App.jsx, frontend/src/components/journal/JournalEntry.jsx, frontend/src/pages/HomePage.jsx, frontend/src/pages/LoginPage.jsx, frontend/src/util/api/auth.js, frontend/src/util/hooks/useAuth.js
Checklist:
No ticket — resolves breaking change
=> hotfix: resolve issue with theme setting before auth

frontend/src/components/journal/JournalEntry.jsx
Checklist:
Closes #290
- fix coin balance not showing on journal entries
- fixe colors for edit/write icon to better match across various themes
=> Bug [Fix]: clean up errors after merge conflict & fix coins balance not showing

frontend/src/App.jsx, frontend/src/pages/JournalCollectionPage.jsx
Checklist:
Closes #285 
- update props to ensure that logout button shows on `JournalCollectionPage.jsx`
- removes unnecessary log from `App.jsx`
=> Bug [Fix]: add logout button to collection list

README.md
=> Docs: add image of application homepage to README.md

frontend/src/pages/LoginPage.jsx, frontend/src/pages/SignupPage.jsx
=> feat: link on signup and login page for repo

frontend/src/App.jsx
Checklist:
Closes #XXXXX
Changes true to theme in App so something is actually being checked
=> refactor: update visibility check
